version: '3.8'
services:
  rabbit:
    container_name: rabbit
    image: "smilyk/rabbit"
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "/var/lib/rabbitmq"

  mysql:
    container_name: mysql
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - "3333:3306"
    expose:
      - "3333"

  eureka:
    container_name: eureka
    restart: always
    image: smilyk/eureka:latest
    ports:
      - "8761:8761"

  email:
    container_name: email
    image: smilyk/email:latest
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - rabbit
    restart: always

  gateway:
    container_name: gateway
    image: smilyk/zuul-service
    ports:
      - "8011:8011"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - email
      - users
      - children
      - eureka
    restart: on-failure


  users:
    container_name: users
    image: smilyk/users
    ports:
      - "8088:8088"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_users?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    depends_on:
      - rabbit
      - eureka
      - email
      - mysql

  children:
    container_name: children
    image: smilyk/children
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_ch?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    depends_on:
      - rabbit
      - mysql
      - eureka
    restart: on-failure

  scheduler:
    container_name: scheduler
    image: smilyk/sceduler-service
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_scheduler?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    depends_on:
      - rabbit
      - mysql
      - eureka
    restart: on-failure


  tsofim:
    container_name: tsofim
    image: smilyk/tsofim
    ports:
      - "8086:8086"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_tsofim?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&createDatabaseIfNotExist=true
      MODULE: search-module.xml
      BROWSER: firefox
      SELENIUM_HUB: selenium-hub
    depends_on:
      - rabbit
      - mysql
      - eureka
      - users
      - children
      - firefox
    restart: on-failure


  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444




