version: '3.8'
services:
  rabbit:
    container_name: rabbit
    image: "smilyk/rabbit"
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "/var/lib/rabbitmq"

  mysql:
    container_name: mysql
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - "3333:3306"
    expose:
      - "3333"

  eureka:
    container_name: eureka
    restart: always
    image: smilyk/eureka:latest
    ports:
      - "8761:8761"

  email:
    container_name: email
    image: smilyk/email:latest
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - rabbit
    restart: always


