version: '3.8'
services:
  rabbit:
    container_name: rabbit
    image: "smilyk/rabbit"
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "/var/lib/rabbitmq"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    hostname: zipkin

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure

  mysql:
    container_name: mysql
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - "3333:3306"
    expose:
      - "3333"


  eureka:
    container_name: eureka
    restart: always
    image: smilyk/eureka:latest
    ports:
      - "8761:8761"

  email:
    container_name: email
    image: smilyk/email
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - rabbit
    restart: always
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  gateway:
    container_name: gateway
    image: smilyk/zuul
    ports:
      - "8011:8011"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - email
      - users
      - children
      - eureka
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"


  users:
    container_name: users
    image: smilyk/users
    ports:
      - "8088:8088"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_users?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    depends_on:
      - rabbit
      - eureka
      - email
      - mysql
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  children:
    container_name: children
    image: smilyk/children
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_ch?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    depends_on:
      - rabbit
      - mysql
      - eureka
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  scheduler:
    container_name: scheduler
    image: smilyk/scheduler
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_scheduler?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    depends_on:
      - rabbit
      - mysql
      - eureka
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"


  tsofim:
    container_name: tsofim
    image: smilyk/tsofim
    ports:
      - "8086:8086"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://user:password@eureka:8761/eureka"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "r00t"
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3333/a_b_tsofim?useUnicode=true&character-set-server=utf8mb4&collation-server=utf8mb4_unicode_ci&serverTimezone=UTC&createDatabaseIfNotExist=true
      MODULE: search-module.xml
      BROWSER: firefox
      SELENIUM_HUB: selenium-hub
    depends_on:
      - rabbit
      - mysql
      - eureka
      - users
      - children
      - firefox
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"


  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444




